#!/usr/bin/python3

import amulet
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.kafka_host = '192.168.0.1:5044'
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:ubuntu')
        self.d.add('packetbeat')
        self.d.relate('packetbeat:beats-host', 'ubuntu:juju-info')
        self.d.configure('packetbeat', {'kafka_hosts': self.kafka_host})

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.packetbeat = self.d.sentry['packetbeat'][0]

    def test_kafka_host_in_templating(self):
        config = self.packetbeat.file_contents('/etc/packetbeat/packetbeat.yml')
        self.assertTrue(self.kafka_host in config)

if __name__ == "__main__":
    unittest.main()
